-- ==============================================================================
-- GSAVE+ SUPABASE BACKEND SCHEMA & ROW LEVEL SECURITY (RLS) POLICIES
-- Multi-user Shared Household Partner Vault and Shared Transaction Access
-- ==============================================================================

-- 1. PROFILES TABLE
-- Stores user profile data linked to auth.users
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE,
    name TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile"
    ON public.profiles
    FOR SELECT
    USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile"
    ON public.profiles
    FOR INSERT
    WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
    ON public.profiles
    FOR UPDATE
    USING (auth.uid() = id);

-- 2. PARTNER VAULTS TABLE
-- Stores shared vaults and invite codes created by user 1 (owner) or linked to user 2 (partner)
CREATE TABLE IF NOT EXISTS public.partner_vaults (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vault_name TEXT NOT NULL,
    invite_code TEXT UNIQUE NOT NULL,
    creator_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    partner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    creator_name TEXT DEFAULT 'Owner',
    partner_name TEXT,
    is_connected BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on partner_vaults
ALTER TABLE public.partner_vaults ENABLE ROW LEVEL SECURITY;

-- Partner Vault Policies:
-- Users can read a vault if they created it, joined it, OR if they are querying by invite code to link
DROP POLICY IF EXISTS "Vault members and code linkers can view vaults" ON public.partner_vaults;
CREATE POLICY "Vault members and code linkers can view vaults"
    ON public.partner_vaults
    FOR SELECT
    USING (
        auth.uid() = creator_id 
        OR auth.uid() = partner_id 
        OR is_connected = false
    );

-- Creator can insert their vault
DROP POLICY IF EXISTS "Authenticated users can create partner vaults" ON public.partner_vaults;
CREATE POLICY "Authenticated users can create partner vaults"
    ON public.partner_vaults
    FOR INSERT
    WITH CHECK (auth.uid() = creator_id);

-- Members or partner linking the code can update the vault
DROP POLICY IF EXISTS "Members can update partner vault" ON public.partner_vaults;
CREATE POLICY "Members can update partner vault"
    ON public.partner_vaults
    FOR UPDATE
    USING (
        auth.uid() = creator_id 
        OR auth.uid() = partner_id 
        OR (partner_id IS NULL AND is_connected = false)
    );

-- 3. WALLETS TABLE
-- Supports personal wallets and shared household wallets
CREATE TABLE IF NOT EXISTS public.wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    vault_id UUID REFERENCES public.partner_vaults(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    type TEXT DEFAULT 'Cash',
    balance NUMERIC(12, 2) DEFAULT 0.00,
    is_shared BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on wallets
ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own wallets or shared vault wallets" ON public.wallets;
CREATE POLICY "Users can read own wallets or shared vault wallets"
    ON public.wallets
    FOR SELECT
    USING (
        auth.uid() = owner_id
        OR is_shared = true
        OR (
            vault_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.partner_vaults pv
                WHERE pv.id = wallets.vault_id
                AND (pv.creator_id = auth.uid() OR pv.partner_id = auth.uid())
            )
        )
    );

DROP POLICY IF EXISTS "Users can insert own or shared wallets" ON public.wallets;
CREATE POLICY "Users can insert own or shared wallets"
    ON public.wallets
    FOR INSERT
    WITH CHECK (
        auth.uid() = owner_id
        OR is_shared = true
        OR owner_id IS NULL
    );

DROP POLICY IF EXISTS "Users can update own or shared vault wallets" ON public.wallets;
CREATE POLICY "Users can update own or shared vault wallets"
    ON public.wallets
    FOR UPDATE
    USING (
        auth.uid() = owner_id
        OR is_shared = true
        OR (
            vault_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.partner_vaults pv
                WHERE pv.id = wallets.vault_id
                AND (pv.creator_id = auth.uid() OR pv.partner_id = auth.uid())
            )
        )
    );

-- 4. TRANSACTIONS TABLE & SHARED RLS ACCESS
-- Allows transactions to be shared across partner vault members
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    wallet_id BIGINT REFERENCES public.wallets(id) ON DELETE CASCADE,
    vault_id UUID REFERENCES public.partner_vaults(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    type TEXT NOT NULL, -- 'Income', 'Withdrawal', 'Bill', 'Loan'
    category TEXT DEFAULT 'General',
    date BIGINT NOT NULL,
    recurring_type TEXT DEFAULT 'None',
    recurring_count INT DEFAULT 0,
    is_paid BOOLEAN DEFAULT true,
    is_shared BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on transactions
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- Transaction Shared Access Policy:
-- A user can SELECT/READ transactions if:
-- 1) They are the transaction creator (user_id = auth.uid())
-- 2) The transaction is marked shared (is_shared = true)
-- 3) The transaction belongs to a shared partner vault where the user is creator or partner
-- 4) The transaction belongs to a wallet that is shared or in a mutual vault
DROP POLICY IF EXISTS "Allow shared partner access to transactions" ON public.transactions;
CREATE POLICY "Allow shared partner access to transactions"
    ON public.transactions
    FOR SELECT
    USING (
        auth.uid() = user_id
        OR is_shared = true
        OR (
            vault_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.partner_vaults pv
                WHERE pv.id = transactions.vault_id
                AND (pv.creator_id = auth.uid() OR pv.partner_id = auth.uid())
            )
        )
        OR (
            wallet_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.wallets w
                WHERE w.id = transactions.wallet_id
                AND (
                    w.is_shared = true
                    OR w.owner_id = auth.uid()
                    OR EXISTS (
                        SELECT 1 FROM public.partner_vaults pv
                        WHERE pv.id = w.vault_id
                        AND (pv.creator_id = auth.uid() OR pv.partner_id = auth.uid())
                    )
                )
            )
        )
    );

-- Policy to Insert Transactions
DROP POLICY IF EXISTS "Allow users to insert personal and shared transactions" ON public.transactions;
CREATE POLICY "Allow users to insert personal and shared transactions"
    ON public.transactions
    FOR INSERT
    WITH CHECK (
        auth.uid() = user_id
        OR user_id IS NULL
        OR is_shared = true
        OR (
            vault_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.partner_vaults pv
                WHERE pv.id = transactions.vault_id
                AND (pv.creator_id = auth.uid() OR pv.partner_id = auth.uid())
            )
        )
    );

-- Policy to Update Transactions (Creator or Mutual Vault Partner)
DROP POLICY IF EXISTS "Allow users and partners to update shared transactions" ON public.transactions;
CREATE POLICY "Allow users and partners to update shared transactions"
    ON public.transactions
    FOR UPDATE
    USING (
        auth.uid() = user_id
        OR is_shared = true
        OR (
            vault_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.partner_vaults pv
                WHERE pv.id = transactions.vault_id
                AND (pv.creator_id = auth.uid() OR pv.partner_id = auth.uid())
            )
        )
    );

-- Policy to Delete Transactions
DROP POLICY IF EXISTS "Allow users and partners to delete transactions" ON public.transactions;
CREATE POLICY "Allow users and partners to delete transactions"
    ON public.transactions
    FOR DELETE
    USING (
        auth.uid() = user_id
        OR is_shared = true
        OR (
            vault_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.partner_vaults pv
                WHERE pv.id = transactions.vault_id
                AND (pv.creator_id = auth.uid() OR pv.partner_id = auth.uid())
            )
        )
    );

-- ==============================================================================
-- STORED PROCEDURE / RPC: Link Two Users via Partner Invite Code
-- Links partner user to the vault, marks is_connected = true, and assigns partner_id
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.link_partner_vault(
    p_invite_code TEXT,
    p_partner_name TEXT DEFAULT 'Partner'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_vault RECORD;
    v_partner_uid UUID;
BEGIN
    v_partner_uid := auth.uid();

    -- Normalize invite code
    p_invite_code := UPPER(TRIM(p_invite_code));

    -- Find vault by invite code
    SELECT * INTO v_vault
    FROM public.partner_vaults
    WHERE UPPER(TRIM(invite_code)) = p_invite_code;

    IF NOT FOUND THEN
        RETURN jsonb_build_object(
            'success', false,
            'message', 'Invite code not found. Please check the 6-digit code.'
        );
    END IF;

    -- Prevent linking to yourself if authenticated
    IF v_partner_uid IS NOT NULL AND v_vault.creator_id = v_partner_uid THEN
        RETURN jsonb_build_object(
            'success', false,
            'message', 'You cannot link your own generated invite code.'
        );
    END IF;

    -- Update the vault to establish the link between both partners
    UPDATE public.partner_vaults
    SET 
        partner_id = COALESCE(v_partner_uid, partner_id),
        partner_name = p_partner_name,
        is_connected = true,
        updated_at = now()
    WHERE id = v_vault.id;

    -- Return success payload
    RETURN jsonb_build_object(
        'success', true,
        'vault_id', v_vault.id,
        'vault_name', v_vault.vault_name,
        'invite_code', v_vault.invite_code,
        'partner_name', p_partner_name,
        'is_connected', true,
        'message', 'Successfully linked partner vault!'
    );
END;
$$;
